
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Arg0n
 */
public class CheckoutSystem extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutSystem
     */
    public CheckoutSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CashPayment = new javax.swing.JFrame();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        Buttonpoint = new javax.swing.JButton();
        Buttonclear = new javax.swing.JButton();
        cashPayButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        txtChange = new javax.swing.JTextField();
        jPanel = new javax.swing.JPanel();
        jPanel.setVisible(false);
        jLabel4 = new javax.swing.JLabel();
        cashYesButton = new javax.swing.JButton();
        cashNoButton = new javax.swing.JButton();
        txtCashTotal = new javax.swing.JLabel();
        CardPayment = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCvc = new javax.swing.JTextField();
        txtCardholderName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        cardPayButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel3.setVisible(false);
        jLabel10 = new javax.swing.JLabel();
        cardYesButton = new javax.swing.JButton();
        cardNoButton = new javax.swing.JButton();
        txtPaymentConfirmed = new javax.swing.JLabel();
        txtCardTotal = new javax.swing.JLabel();
        CheckPayment = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        txtCheckTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCheckNumber = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        checkPayButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel4.setVisible(false);
        jLabel14 = new javax.swing.JLabel();
        checkYesButton = new javax.swing.JButton();
        checkNoButton = new javax.swing.JButton();
        txtCheckPaymentConfirmed = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCheckChange = new javax.swing.JLabel();
        LoyalityP = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        phoneNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        qtyLabel = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        itemScanLabel1 = new javax.swing.JLabel();
        subTotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        itemId = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        removeItemButton1 = new javax.swing.JButton();
        cashButton = new javax.swing.JButton();
        totalButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        creditPoints = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtTillStatus = new javax.swing.JLabel();
        buttonClose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();

        CashPayment.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CashPayment.setTitle("Cash Payment");
        CashPayment.setLocationByPlatform(true);
        CashPayment.setMinimumSize(new java.awt.Dimension(795, 620));
        CashPayment.setResizable(false);
        CashPayment.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 34, 67, 87));

        Button8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 34, 67, 87));

        Button9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 34, 67, 87));

        Button4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 139, 67, 87));

        Button5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 139, 67, 87));

        Button6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 139, 67, 87));

        Button1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 245, 67, 87));

        Button2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 245, 67, 87));

        Button3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 245, 67, 87));

        Button0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 67, 87));

        Buttonpoint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Buttonpoint.setText(".");
        Buttonpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpointActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Buttonpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 350, 67, 87));

        Buttonclear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Buttonclear.setText("C");
        Buttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonclearActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(Buttonclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 67, 87));

        cashPayButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cashPayButton.setText("PAY");
        cashPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPayButtonActionPerformed(evt);
            }
        });
        CashPayment.getContentPane().add(cashPayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 483, 237, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TOTAL :");
        CashPayment.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 34, 114, 87));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("CHANGE :");
        CashPayment.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 245, 129, 87));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("CASH :");
        CashPayment.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 139, 114, 87));

        txtCash.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CashPayment.getContentPane().add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 157, 175, 52));

        txtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CashPayment.getContentPane().add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 263, 175, 52));

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Print Receipt?");
        jPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 0, -1, -1));

        cashYesButton.setBackground(new java.awt.Color(153, 255, 153));
        cashYesButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cashYesButton.setText("Yes");
        cashYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashYesButtonActionPerformed(evt);
            }
        });
        jPanel.add(cashYesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 47, 85, 73));

        cashNoButton.setBackground(new java.awt.Color(255, 102, 102));
        cashNoButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cashNoButton.setText("No");
        cashNoButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                cashNoButtonComponentHidden(evt);
            }
        });
        cashNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashNoButtonActionPerformed(evt);
            }
        });
        jPanel.add(cashNoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 48, 83, 71));

        CashPayment.getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 398, 500, 190));

        txtCashTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CashPayment.getContentPane().add(txtCashTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 180, 50));

        CardPayment.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CardPayment.setTitle("Card Payment");
        CardPayment.setLocationByPlatform(true);
        CardPayment.setMinimumSize(new java.awt.Dimension(900, 620));
        CardPayment.setResizable(false);
        CardPayment.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("CVC");
        CardPayment.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 160, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("TOTAL :");
        CardPayment.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 114, 87));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Card Information");
        CardPayment.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 87));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Cardholder Name");
        CardPayment.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 50));

        txtCvc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCvcActionPerformed(evt);
            }
        });
        CardPayment.getContentPane().add(txtCvc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 100, 50));

        txtCardholderName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCardholderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardholderNameActionPerformed(evt);
            }
        });
        CardPayment.getContentPane().add(txtCardholderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 570, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Card number");
        CardPayment.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 50));

        txtCardNumber.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardNumberActionPerformed(evt);
            }
        });
        CardPayment.getContentPane().add(txtCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 410, 50));

        cardPayButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cardPayButton.setText("PAY");
        cardPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardPayButtonActionPerformed(evt);
            }
        });
        CardPayment.getContentPane().add(cardPayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 237, 65));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Print Receipt?");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardYesButton.setBackground(new java.awt.Color(153, 255, 153));
        cardYesButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cardYesButton.setText("Yes");
        cardYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardYesButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cardYesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 85, 73));

        cardNoButton.setBackground(new java.awt.Color(255, 102, 102));
        cardNoButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cardNoButton.setText("No");
        cardNoButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                cardNoButtonComponentHidden(evt);
            }
        });
        cardNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNoButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cardNoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 83, 71));

        CardPayment.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 350, 160));

        txtPaymentConfirmed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPaymentConfirmed.setForeground(new java.awt.Color(255, 0, 0));
        CardPayment.getContentPane().add(txtPaymentConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 450, 40));

        txtCardTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CardPayment.getContentPane().add(txtCardTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 150, 50));

        CheckPayment.setMinimumSize(new java.awt.Dimension(899, 524));
        CheckPayment.setResizable(false);
        CheckPayment.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("TOTAL :");
        CheckPayment.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 114, 87));

        txtCheckTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CheckPayment.getContentPane().add(txtCheckTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 180, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Check Number");
        CheckPayment.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, 50));

        txtCheckNumber.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCheckNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckNumberActionPerformed(evt);
            }
        });
        CheckPayment.getContentPane().add(txtCheckNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 520, 50));

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        CheckPayment.getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 160, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("Amount");
        CheckPayment.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 160, 60));

        checkPayButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        checkPayButton.setText("PAY");
        checkPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPayButtonActionPerformed(evt);
            }
        });
        CheckPayment.getContentPane().add(checkPayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 237, 65));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Print Receipt?");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        checkYesButton.setBackground(new java.awt.Color(153, 255, 153));
        checkYesButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkYesButton.setText("Yes");
        checkYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkYesButtonActionPerformed(evt);
            }
        });
        jPanel4.add(checkYesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 85, 73));

        checkNoButton.setBackground(new java.awt.Color(255, 102, 102));
        checkNoButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkNoButton.setText("No");
        checkNoButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                checkNoButtonComponentHidden(evt);
            }
        });
        checkNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNoButtonActionPerformed(evt);
            }
        });
        jPanel4.add(checkNoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 83, 71));

        CheckPayment.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 330, 160));

        txtCheckPaymentConfirmed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCheckPaymentConfirmed.setForeground(new java.awt.Color(255, 0, 0));
        CheckPayment.getContentPane().add(txtCheckPaymentConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 340, 50));

        jPanel5.setVisible(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Change :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 114, 50));

        txtCheckChange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCheckChange.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(txtCheckChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 140, 50));

        CheckPayment.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 360, 90));

        LoyalityP.setVisible(false);
        LoyalityP.setMinimumSize(new java.awt.Dimension(640, 380));
        LoyalityP.setResizable(false);
        LoyalityP.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Loyality Program");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(104, 104, 104))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        LoyalityP.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        okButton.setBackground(new java.awt.Color(255, 102, 0));
        okButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        okButton.setForeground(new java.awt.Color(255, 255, 255));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        LoyalityP.getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 119, 66));

        phoneNo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        phoneNo.setForeground(new java.awt.Color(255, 102, 0));
        LoyalityP.getContentPane().add(phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 315, 43));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("Phone Number: ");
        LoyalityP.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 1050));
        setPreferredSize(new java.awt.Dimension(1030, 1050));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalLabel.setText("Total");
        jPanel1.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 140, 40));

        qtyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        qtyLabel.setText("QTY");
        jPanel1.add(qtyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 12, -1, -1));

        qty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qty.setText("1");
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 11, 47, 40));

        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 11, 49, 40));

        jTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ITEM", "QTY", "AMOUNT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.setRowHeight(20);
        jTable.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 530, 430));

        itemScanLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        itemScanLabel1.setText("Item Scan");
        jPanel1.add(itemScanLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        subTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subTotalLabel.setText("Sub Total");
        jPanel1.add(subTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        taxLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        taxLabel.setText("Tax");
        jPanel1.add(taxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        itemId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdActionPerformed(evt);
            }
        });
        jPanel1.add(itemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 11, 200, 40));

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 140, 40));

        txtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 140, 40));

        clearButton.setBackground(new java.awt.Color(255, 102, 102));
        clearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 130, 70));

        removeItemButton1.setBackground(new java.awt.Color(255, 153, 51));
        removeItemButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeItemButton1.setText("Remove Item");
        removeItemButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(removeItemButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 130, 70));

        cashButton.setBackground(new java.awt.Color(153, 255, 153));
        cashButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cashButton.setText("Cash");
        cashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cashButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 150, 100));

        totalButton1.setBackground(new java.awt.Color(255, 153, 51));
        totalButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalButton1.setText("Total");
        totalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(totalButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 130, 80));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 150, 100));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Credit/Debit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 190, 100));

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Scale");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 130, 80));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 370, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 370, 10));

        creditPoints.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        creditPoints.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.add(creditPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("Credit Points :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setText("Till Status");

        txtTillStatus.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtTillStatus.setForeground(new java.awt.Color(255, 0, 0));
        txtTillStatus.setText("CLOSED");

        buttonClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(txtTillStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTillStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 730, 290, 190));

        receipt.setColumns(20);
        receipt.setRows(5);
        receipt.setMargin(new java.awt.Insets(15, 15, 15, 15));
        jScrollPane2.setViewportView(receipt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 380, 440));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Last Printed Receipt");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 950, 980));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try{
            int inputItemId = Integer.parseInt(itemId.getText());
            itemId.setText("");
        
            int inputQty = Integer.parseInt(qty.getText());
            qty.setText("1");
            //Throw exception
            DatabaseFunctions dbfunc = new DatabaseFunctions();
            String[] item = dbfunc.getItem(inputItemId);
        
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.addRow(new Object[]{inputItemId,item[0],inputQty,Float.parseFloat(item[1])*inputQty});
            if(jTable.getRowCount() == 1){
            LoyalityP.setVisible(true);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Item not found");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        resetAction();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void removeItemButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        
        int RemoveItem = jTable.getSelectedRow();
        if(RemoveItem >= 0)
        {
            model.removeRow(RemoveItem);
        }
    }//GEN-LAST:event_removeItemButton1ActionPerformed

    private void itemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void cashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashButtonActionPerformed
        if (txtTotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Get totaled before payment");
        }
        else{
            CashPayment.setVisible(true);
            txtCashTotal.setText(txtTotal.getText());
        }
    }//GEN-LAST:event_cashButtonActionPerformed

    private void totalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalButton1ActionPerformed
        itemCost();
    }//GEN-LAST:event_totalButton1ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button7.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button7.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button8.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button8.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button9.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button9.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button4.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button4.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button5.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button5.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button6.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button6.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button1.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button1.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button2.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button2.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button3.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button3.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        // TODO add your handling code here:
        String Enternumber = txtCash.getText();

        if (Enternumber == ""){
            txtCash.setText(Button0.getText());
        }
        else{
            Enternumber = txtCash.getText() + Button0.getText();
            txtCash.setText(Enternumber);
        }
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpointActionPerformed
        // TODO add your handling code here:
        if(! txtCash.getText().contains(".")){
            txtCash.setText(txtCash.getText() + Buttonpoint.getText());
        }
    }//GEN-LAST:event_ButtonpointActionPerformed

    private void ButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonclearActionPerformed
        // TODO add your handling code here:
        txtCash.setText("");
        txtChange.setText("");

    }//GEN-LAST:event_ButtonclearActionPerformed

    private void cashPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPayButtonActionPerformed
        String str = txtCashTotal.getText();
        str = str.replaceAll("[^\\.0123456789]","");
        double total = Double.parseDouble(str);
        double cash = Double.parseDouble(txtCash.getText());
        double cChange = (cash - total);

        if(cash >= total){
            Random rand = new Random(); //instance of random class
            //generate random values from 0-24
            int int_random = rand.nextInt(2147483646);
            String itemAmt = itemAmount();
//            System.out.println(itemAmt);
            String itemList = itemId();
//            System.out.println(itemList);
            CheckoutControl.cash(total,cash,itemAmt,itemList,int_random);
            String ChangeAmt = String.format("$ %.2f", cChange);
            txtChange.setText(ChangeAmt);
            try{
                DatabaseFunctions.updateCredit(Long.parseLong(phoneNo.getText()), total);
            }
            catch(Exception e){
                
            }
            jPanel.setVisible(true);
            txtTillStatus.setText("OPEN");
        }
        else{
            JOptionPane.showMessageDialog(this, "Not enough Cash");
            txtCash.setText("");
            txtChange.setText("");
        }
        
    }//GEN-LAST:event_cashPayButtonActionPerformed

    private void cashNoButtonComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cashNoButtonComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_cashNoButtonComponentHidden

    private void cashNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashNoButtonActionPerformed
        txtCashTotal.setText("");
        txtCash.setText("");
        txtChange.setText("");
        resetAction();
        CashPayment.dispose();
    }//GEN-LAST:event_cashNoButtonActionPerformed

    private void cashYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashYesButtonActionPerformed
        receipt();
        receipt.setText(receipt.getText() + "\t"+"\t"+"Cash :"+"\t"+ "$ " + txtCash.getText() + "\n");
        receipt.setText(receipt.getText() + "\t"+"\t"+"Change :"+"\t"+ txtChange.getText() + "\n");
        receipt.setText(receipt.getText() + "\n");
        receipt.setText(receipt.getText() + "                                       THANK YOU                      \n");
        txtCashTotal.setText("");
        txtCash.setText("");
        txtChange.setText("");
        resetAction();
        CashPayment.dispose();
    }//GEN-LAST:event_cashYesButtonActionPerformed

    private void txtCvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCvcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCvcActionPerformed

    private void txtCardholderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardholderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardholderNameActionPerformed

    private void txtCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardNumberActionPerformed

    private void cardPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardPayButtonActionPerformed
        String str = txtCardTotal.getText();
        str = str.replaceAll("[^\\.0123456789]","");
        double total = Double.parseDouble(str);
        Random rand = new Random(); //instance of random class
        //generate random values from 0-24
        int int_random = rand.nextInt(2147483646);
        String itemAmt = itemAmount();
        String itemList = itemId();
        boolean confirm = CheckoutControl.card(total, Long.parseLong(txtCardNumber.getText()),Integer.parseInt(txtCvc.getText()) , itemAmt,itemList,int_random);
        if (confirm == true){
            txtPaymentConfirmed.setText("APPROVED");
            try{
                DatabaseFunctions.updateCredit(Long.parseLong(phoneNo.getText()), total);
            }
            catch(Exception e){
                
            }
            jPanel3.setVisible(true);
        }
        else{
            txtPaymentConfirmed.setText("Error Processing Transaction. Try Again.");
        }
    }//GEN-LAST:event_cardPayButtonActionPerformed

    private void cardYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardYesButtonActionPerformed
        receipt();
        receipt.setText(receipt.getText() + "\t"+"\t"+"Card :"+"\t"+ txtCardNumber.getText() + "\n");
        receipt.setText(receipt.getText() + "\n");
        receipt.setText(receipt.getText() + "                                       THANK YOU                      \n");
        txtCardTotal.setText("");
        txtCardNumber.setText("");
        txtCvc.setText("");
        txtCardholderName.setText("");
        resetAction();
        CardPayment.dispose();
    }//GEN-LAST:event_cardYesButtonActionPerformed

    private void cardNoButtonComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cardNoButtonComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNoButtonComponentHidden

    private void cardNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNoButtonActionPerformed
        txtCardTotal.setText("");
        txtCardNumber.setText("");
        txtCvc.setText("");
        txtCardholderName.setText("");
        resetAction();
        CardPayment.dispose();
    }//GEN-LAST:event_cardNoButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txtTotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Get totaled before payment");
        }
        else{
            CardPayment.setVisible(true);
            txtCardTotal.setText(txtTotal.getText());            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCheckNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckNumberActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void checkPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPayButtonActionPerformed
        String str = txtCheckTotal.getText();
        str = str.replaceAll("[^\\.0123456789]","");
        double total = Double.parseDouble(str);
        Random rand = new Random(); //instance of random class
        //generate random values from 0-24
        int int_random = rand.nextInt(2147483646);
        String itemAmt = itemAmount();
        String itemList = itemId();
        boolean validity = CheckoutControl.check(total, Long.parseLong(txtCheckNumber.getText()), itemAmt,itemList,int_random);
        if (validity == true){
            txtCheckPaymentConfirmed.setText("Valid Check");
            String strTotal = txtCheckTotal.getText();
            strTotal = strTotal.replaceAll("[^\\.0123456789]","");
            double totalAmt = Double.parseDouble(strTotal);
            double checkAmt = Double.parseDouble(txtAmount.getText());
            double checkChange = (checkAmt - totalAmt);
        
            String checkChangeAmt = String.format("$ %.2f", checkChange);
            txtCheckChange.setText(checkChangeAmt);
            try{
                DatabaseFunctions.updateCredit(Long.parseLong(phoneNo.getText()), total);
            }
            catch(Exception e){
                
            }
            jPanel5.setVisible(true);
            jPanel4.setVisible(true);
        }
        else{
            txtCheckPaymentConfirmed.setText("Invalid Check.");
        } 
    }//GEN-LAST:event_checkPayButtonActionPerformed

    private void checkYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkYesButtonActionPerformed
        receipt();
        receipt.setText(receipt.getText() + "\t"+"\t"+"Check :"+"\t"+ txtCheckNumber.getText() + "\n");
        receipt.setText(receipt.getText() + "\t"+"\t"+"Amount :"+"\t"+"$ "+ txtAmount.getText() + "\n"); 
        receipt.setText(receipt.getText() + "\t"+"\t"+"Change :"+"\t"+ txtCheckChange.getText() + "\n");
        receipt.setText(receipt.getText() + "\n");
        receipt.setText(receipt.getText() + "                                       THANK YOU                      \n");
        txtCheckTotal.setText("");
        txtCheckChange.setText("");
        txtCheckNumber.setText("");
        txtAmount.setText("");
        resetAction();
        CheckPayment.dispose();
    }//GEN-LAST:event_checkYesButtonActionPerformed

    private void checkNoButtonComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_checkNoButtonComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNoButtonComponentHidden

    private void checkNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNoButtonActionPerformed
        txtCheckTotal.setText("");
        txtCheckChange.setText("");
        txtCheckNumber.setText("");
        txtAmount.setText("");
        resetAction();
        CheckPayment.dispose();
    }//GEN-LAST:event_checkNoButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txtTotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Get totaled before payment");
        }
        else{
            CheckPayment.setVisible(true);
            txtCheckTotal.setText(txtTotal.getText());           
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try{
            double[] cP = DatabaseFunctions.checkLoyalty(Long.parseLong(phoneNo.getText()));
            creditPoints.setText(String.valueOf(cP[1]));
            LoyalityP.dispose();
        }
        catch (Exception e){
            LoyalityP.dispose();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        txtTillStatus.setText("CLOSED");
    }//GEN-LAST:event_buttonCloseActionPerformed

    public  double itemCost(){
        double sum = 0;
        for (int i = 0; i <jTable.getRowCount();i++){
            sum = sum + Double.parseDouble(jTable.getValueAt(i, 3).toString());
        }
        txtSubtotal.setText(Double.toString(sum));
        double cSubtotal = Double.parseDouble(txtSubtotal.getText());
        
        double cTax = (cSubtotal * 8)/100;
        String displayTax = String.format("$ %.2f", cTax);
        txtTax.setText(displayTax);
        
        String displaySubtotal = String.format("$ %.2f", cSubtotal);
        txtSubtotal.setText(displaySubtotal);
        
        double cTotal = cSubtotal + cTax;
        String displayTotal = String.format("$ %.2f", cTotal);
        txtTotal.setText(displayTotal);
        
        return(cTotal);
    }
    
        public void receipt(){
        String itotal = txtTotal.getText();
        
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        receipt.setText("");
        receipt.setText(receipt.getText() + "*********************************************************\n");
        receipt.setText(receipt.getText() + "*                       Checkout System                        *\n");
        receipt.setText(receipt.getText() + "*********************************************************\n");
        receipt.setText(receipt.getText() + "Product"+"\t"+"QTY"+"\t"+"Amount"+"\n");
        
        for(int i = 0; i< model.getRowCount();i++){
            String product = model.getValueAt(i,1).toString();
            String QTY = model.getValueAt(i,2).toString();
            String amount = model.getValueAt(i,3).toString();
            receipt.setText(receipt.getText() + product +"\t"+ QTY +"\t"+ amount +"\n");
        }
        receipt.setText(receipt.getText() + "\n");
        receipt.setText(receipt.getText() + "\t"+"\t"+"Total :"+"\t"+ itotal + "\n");
    }
    
    
    public void resetAction(){
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0);
        txtTax.setText("");
        txtTotal.setText("");
        txtSubtotal.setText("");
        phoneNo.setText("");
        creditPoints.setText("");
        
    }
    
    public String itemAmount(){
        String amt = jTable.getValueAt(0,2).toString();
        for (int i = 1; i< jTable.getRowCount();i++){
            amt = amt + ", " + jTable.getValueAt(i,2).toString();
    }
        return amt;
    }
    
    public String itemId(){
        String id = jTable.getValueAt(0,0).toString();
        for (int i = 1; i< jTable.getRowCount();i++){
            id = id + ", " + jTable.getValueAt(i,0).toString();
    }
        return id;
    }   
    
 
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckoutSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckoutSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckoutSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckoutSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckoutSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton Buttonclear;
    private javax.swing.JButton Buttonpoint;
    private javax.swing.JFrame CardPayment;
    private javax.swing.JFrame CashPayment;
    private javax.swing.JFrame CheckPayment;
    private javax.swing.JFrame LoyalityP;
    private javax.swing.JButton addButton;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton cardNoButton;
    private javax.swing.JButton cardPayButton;
    private javax.swing.JButton cardYesButton;
    private javax.swing.JButton cashButton;
    private javax.swing.JButton cashNoButton;
    private javax.swing.JButton cashPayButton;
    private javax.swing.JButton cashYesButton;
    private javax.swing.JButton checkNoButton;
    private javax.swing.JButton checkPayButton;
    private javax.swing.JButton checkYesButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel creditPoints;
    private javax.swing.JTextField itemId;
    private javax.swing.JLabel itemScanLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JTextArea receipt;
    private javax.swing.JButton removeItemButton1;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JButton totalButton1;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JLabel txtCardTotal;
    private javax.swing.JTextField txtCardholderName;
    private javax.swing.JTextField txtCash;
    private javax.swing.JLabel txtCashTotal;
    private javax.swing.JTextField txtChange;
    private javax.swing.JLabel txtCheckChange;
    private javax.swing.JTextField txtCheckNumber;
    private javax.swing.JLabel txtCheckPaymentConfirmed;
    private javax.swing.JLabel txtCheckTotal;
    private javax.swing.JTextField txtCvc;
    private javax.swing.JLabel txtPaymentConfirmed;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JLabel txtTillStatus;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
