import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Arg0n
 */
public class StoreManagement extends javax.swing.JFrame {

    /**
     * Creates new form StoreManagement
     */
    public StoreManagement() {
        initComponents();
        DisplayTable();
    }
    
    private static java.sql.Connection c = null;
    
    public static java.sql.Connection connect() throws Exception {
        if (c == null) {
            c = (java.sql.Connection) DriverManager.getConnection("jdbc:sqlite::resource:store.db");
        } else {
            c.close();
            c = (java.sql.Connection) DriverManager.getConnection("jdbc:sqlite::resource:store.db");
        }
        return c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        Account = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAccName = new javax.swing.JTextField();
        txtAccPin = new javax.swing.JTextField();
        txtAccPhoneNo = new javax.swing.JTextField();
        txtAccRole = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        buttonAccAdd = new javax.swing.JButton();
        buttonAccDelete = new javax.swing.JButton();
        buttonAccClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccount = new javax.swing.JTable();
        Inventory = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtInvName = new javax.swing.JTextField();
        txtInvDiscount = new javax.swing.JTextField();
        txtInvManufacturer = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtInvPrice = new javax.swing.JTextField();
        txtInvThreshold = new javax.swing.JTextField();
        txtInvInventoryNo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        buttonInvAdd = new javax.swing.JButton();
        buttonInvDelete = new javax.swing.JButton();
        buttonInvClear = new javax.swing.JButton();
        buttonInvUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInventory = new javax.swing.JTable();
        Orders = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtOrdStatus = new javax.swing.JTextField();
        txtItemAmt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        buttonOrdClear = new javax.swing.JButton();
        buttonOrdSend = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        buttonOrdUpdate = new javax.swing.JButton();
        buttonOrdDelete = new javax.swing.JButton();
        buttonOrdApprove = new javax.swing.JButton();
        buttonOrdReceive = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableOrders = new javax.swing.JTable();
        Purchases = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        buttonOrdClear1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePurchase = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        runInv = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 845));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane.setToolTipText("");
        jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N

        Account.setMinimumSize(new java.awt.Dimension(1280, 845));
        Account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 240));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pin");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Role");

        txtAccName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtAccName.setForeground(new java.awt.Color(255, 102, 0));

        txtAccPin.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtAccPin.setForeground(new java.awt.Color(255, 102, 0));

        txtAccPhoneNo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtAccPhoneNo.setForeground(new java.awt.Color(255, 102, 0));

        txtAccRole.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtAccRole.setForeground(new java.awt.Color(255, 102, 0));
        txtAccRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Manager", "Both" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccPin, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAccRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAccPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtAccName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtAccPin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccRole, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Account.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1050, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonAccAdd.setBackground(new java.awt.Color(255, 102, 0));
        buttonAccAdd.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonAccAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAccAdd.setText("Add");
        buttonAccAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccAddActionPerformed(evt);
            }
        });

        buttonAccDelete.setBackground(new java.awt.Color(255, 102, 0));
        buttonAccDelete.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonAccDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonAccDelete.setText("Delete");
        buttonAccDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccDeleteActionPerformed(evt);
            }
        });

        buttonAccClear.setBackground(new java.awt.Color(255, 102, 0));
        buttonAccClear.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonAccClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonAccClear.setText("Clear");
        buttonAccClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(buttonAccAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(buttonAccDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(buttonAccClear, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAccDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAccAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAccClear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        Account.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1050, 130));

        tableAccount.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pin", "Employee", "Manager", "Name", "Phone No", "Loyal Customer", "Credit Points"
            }
        ));
        tableAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableAccount.setRowHeight(30);
        tableAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAccount);
        jScrollPane1.setVisible(true);
        if (tableAccount.getColumnModel().getColumnCount() > 0) {
            tableAccount.getColumnModel().getColumn(1).setMinWidth(4);
            tableAccount.getColumnModel().getColumn(1).setPreferredWidth(4);
            tableAccount.getColumnModel().getColumn(1).setMaxWidth(4);
            tableAccount.getColumnModel().getColumn(2).setMinWidth(4);
            tableAccount.getColumnModel().getColumn(2).setPreferredWidth(4);
            tableAccount.getColumnModel().getColumn(2).setMaxWidth(4);
        }

        Account.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1050, 470));

        jTabbedPane.addTab("Account", Account);

        Inventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(1300, 240));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Discount");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manufacturer");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Current No");

        txtInvName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInvName.setForeground(new java.awt.Color(255, 102, 0));

        txtInvDiscount.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInvDiscount.setForeground(new java.awt.Color(255, 102, 0));

        txtInvManufacturer.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInvManufacturer.setForeground(new java.awt.Color(255, 102, 0));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Price");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Threshold");

        txtInvPrice.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInvPrice.setForeground(new java.awt.Color(255, 102, 0));

        txtInvThreshold.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInvThreshold.setForeground(new java.awt.Color(255, 102, 0));

        txtInvInventoryNo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtInvInventoryNo.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInvPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInvDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInvName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInvInventoryNo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInvThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtInvManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtInvName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInvManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtInvPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInvThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(txtInvInventoryNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        Inventory.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1050, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        buttonInvAdd.setBackground(new java.awt.Color(255, 102, 0));
        buttonInvAdd.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonInvAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonInvAdd.setText("Add");
        buttonInvAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvAddActionPerformed(evt);
            }
        });

        buttonInvDelete.setBackground(new java.awt.Color(255, 102, 0));
        buttonInvDelete.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonInvDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonInvDelete.setText("Delete");
        buttonInvDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvDeleteActionPerformed(evt);
            }
        });

        buttonInvClear.setBackground(new java.awt.Color(255, 102, 0));
        buttonInvClear.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonInvClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonInvClear.setText("Clear");
        buttonInvClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvClearActionPerformed(evt);
            }
        });

        buttonInvUpdate.setBackground(new java.awt.Color(255, 102, 0));
        buttonInvUpdate.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonInvUpdate.setForeground(new java.awt.Color(255, 255, 255));
        buttonInvUpdate.setText("Update");
        buttonInvUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(buttonInvAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(buttonInvUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(buttonInvDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(buttonInvClear, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInvDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInvAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInvClear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInvUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        Inventory.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1050, 130));

        tableInventory.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Item Name", "Item Price", "Manufacturer", "Item Threshhold", "Current Inventory", "Item Discount"
            }
        ));
        tableInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableInventory.setRowHeight(30);
        tableInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInventoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableInventory);
        if (tableInventory.getColumnModel().getColumnCount() > 0) {
            tableInventory.getColumnModel().getColumn(0).setMinWidth(4);
            tableInventory.getColumnModel().getColumn(0).setPreferredWidth(4);
            tableInventory.getColumnModel().getColumn(0).setMaxWidth(4);
            tableInventory.getColumnModel().getColumn(1).setMinWidth(4);
            tableInventory.getColumnModel().getColumn(1).setPreferredWidth(4);
            tableInventory.getColumnModel().getColumn(1).setMaxWidth(4);
            tableInventory.getColumnModel().getColumn(2).setMinWidth(4);
            tableInventory.getColumnModel().getColumn(2).setPreferredWidth(4);
            tableInventory.getColumnModel().getColumn(2).setMaxWidth(4);
        }

        Inventory.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1050, 470));

        jTabbedPane.addTab("Inventory", Inventory);

        Orders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setMinimumSize(new java.awt.Dimension(1300, 240));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status");

        txtOrdStatus.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtOrdStatus.setForeground(new java.awt.Color(255, 102, 0));

        txtItemAmt.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtItemAmt.setForeground(new java.awt.Color(255, 102, 0));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Item Amount");

        buttonOrdClear.setBackground(new java.awt.Color(255, 255, 255));
        buttonOrdClear.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonOrdClear.setForeground(new java.awt.Color(255, 102, 0));
        buttonOrdClear.setText("Clear");
        buttonOrdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdClearActionPerformed(evt);
            }
        });

        buttonOrdSend.setBackground(new java.awt.Color(255, 255, 255));
        buttonOrdSend.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonOrdSend.setForeground(new java.awt.Color(255, 102, 0));
        buttonOrdSend.setText("Send Order");
        buttonOrdSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdSendActionPerformed(evt);
            }
        });

        jScrollPane5.setBorder(null);
        jScrollPane5.setBackground(new java.awt.Color(255, 102, 0));
        jScrollPane5.setForeground(new java.awt.Color(255, 102, 0));

        jTextArea1.setBackground(new java.awt.Color(255, 102, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText(" Status\n     1- waiting for approval\n     2- approved waiting to send\n     3- sent waiting for delivery\n     4- fulfilled");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jTextArea1.setCaretColor(new java.awt.Color(255, 102, 0));
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtOrdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtItemAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonOrdSend, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrdClear, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(buttonOrdClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(buttonOrdSend, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtOrdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtItemAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(26, 26, 26))))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Orders.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1050, 160));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        buttonOrdUpdate.setBackground(new java.awt.Color(255, 102, 0));
        buttonOrdUpdate.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonOrdUpdate.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrdUpdate.setText("Update");
        buttonOrdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdUpdateActionPerformed(evt);
            }
        });

        buttonOrdDelete.setBackground(new java.awt.Color(255, 102, 0));
        buttonOrdDelete.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonOrdDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrdDelete.setText("Delete");
        buttonOrdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdDeleteActionPerformed(evt);
            }
        });

        buttonOrdApprove.setBackground(new java.awt.Color(255, 102, 0));
        buttonOrdApprove.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonOrdApprove.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrdApprove.setText("Approve Order");
        buttonOrdApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdApproveActionPerformed(evt);
            }
        });

        buttonOrdReceive.setBackground(new java.awt.Color(255, 102, 0));
        buttonOrdReceive.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonOrdReceive.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrdReceive.setText("Received Order");
        buttonOrdReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdReceiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(buttonOrdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(buttonOrdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(buttonOrdApprove)
                .addGap(61, 61, 61)
                .addComponent(buttonOrdReceive)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOrdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrdApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrdReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        Orders.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1050, 130));

        tableOrders.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Item Amount", "Item ID", "Status"
            }
        ));
        tableOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableOrders.setRowHeight(30);
        tableOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrdersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableOrders);
        /*
        if (tableOrders.getColumnModel().getColumnCount() > 0) {
            tableOrders.getColumnModel().getColumn(0).setMinWidth(4);
            tableOrders.getColumnModel().getColumn(0).setPreferredWidth(4);
            tableOrders.getColumnModel().getColumn(0).setMaxWidth(4);
            tableOrders.getColumnModel().getColumn(1).setMinWidth(4);
            tableOrders.getColumnModel().getColumn(1).setPreferredWidth(4);
            tableOrders.getColumnModel().getColumn(1).setMaxWidth(4);
            tableOrders.getColumnModel().getColumn(2).setMinWidth(4);
            tableOrders.getColumnModel().getColumn(2).setPreferredWidth(4);
            tableOrders.getColumnModel().getColumn(2).setMaxWidth(4);
        }
        */

        Orders.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1050, 550));

        jTabbedPane.addTab("Orders", Orders);

        Purchases.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 102, 0));
        jPanel7.setMinimumSize(new java.awt.Dimension(1300, 240));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Purchase History");

        buttonOrdClear1.setBackground(new java.awt.Color(255, 255, 255));
        buttonOrdClear1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buttonOrdClear1.setForeground(new java.awt.Color(255, 102, 0));
        buttonOrdClear1.setText("Refresh");
        buttonOrdClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(buttonOrdClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOrdClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        Purchases.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1050, 130));

        tablePurchase.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tablePurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cart ID", "Item Amount", "Total Price", "Item List", "Account ID", "Bank Info"
            }
        ));
        tablePurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablePurchase.setRowHeight(30);
        jScrollPane4.setViewportView(tablePurchase);
        if (tablePurchase.getColumnModel().getColumnCount() > 0) {
            tablePurchase.getColumnModel().getColumn(0).setMinWidth(4);
            tablePurchase.getColumnModel().getColumn(0).setPreferredWidth(4);
            tablePurchase.getColumnModel().getColumn(0).setMaxWidth(4);
            tablePurchase.getColumnModel().getColumn(1).setMinWidth(4);
            tablePurchase.getColumnModel().getColumn(1).setPreferredWidth(4);
            tablePurchase.getColumnModel().getColumn(1).setMaxWidth(4);
            tablePurchase.getColumnModel().getColumn(2).setMinWidth(4);
            tablePurchase.getColumnModel().getColumn(2).setPreferredWidth(4);
            tablePurchase.getColumnModel().getColumn(2).setMaxWidth(4);
        }

        Purchases.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1050, 710));

        jTabbedPane.addTab("Purchase", Purchases);

        jPanel9.setBackground(new java.awt.Color(255, 102, 0));
        jPanel9.setMinimumSize(new java.awt.Dimension(1300, 240));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Inventory Management");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        runInv.setBackground(new java.awt.Color(255, 102, 0));
        runInv.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        runInv.setForeground(new java.awt.Color(255, 255, 255));
        runInv.setText("Run Inventory");
        runInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runInvActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Get the Low inventory items from the inventory and add them to the order list/ orders table with status 1.(waiting for approval)");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(119, 119, 119))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(runInv, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(runInv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Manage", jPanel8);

        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAccAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccAddActionPerformed
        try{
            if(txtAccName.getText().isEmpty() || txtAccPhoneNo.getText().isEmpty() || txtAccPin.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
            }
            else{
                if(txtAccRole.getSelectedItem().toString().equals("Cashier")){
                    DatabaseFunctions.addAccount(Integer.parseInt(txtAccPin.getText()), txtAccName.getText(), true, false, Long.parseLong(txtAccPhoneNo.getText()));
                }
                else if((txtAccRole.getSelectedItem().toString().equals("Manager"))){
                    DatabaseFunctions.addAccount(Integer.parseInt(txtAccPin.getText()), txtAccName.getText(), false, true, Long.parseLong(txtAccPhoneNo.getText()));
                }
                else{
                    DatabaseFunctions.addAccount(Integer.parseInt(txtAccPin.getText()), txtAccName.getText(), true, true, Long.parseLong(txtAccPhoneNo.getText()));
                }
                
                JOptionPane.showMessageDialog(this, "Account Successfully Added");
                DisplayTable();
                txtAccName.setText("");
                txtAccPhoneNo.setText("");
                txtAccPin.setText("");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Input Correct Information");
        }
    }//GEN-LAST:event_buttonAccAddActionPerformed

    private void buttonAccDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccDeleteActionPerformed
        try{
            c = connect();
            DefaultTableModel model = (DefaultTableModel)tableAccount.getModel();
            int tbIndex = tableAccount.getSelectedRow();
            String Id = model.getValueAt(tbIndex, 0).toString();
            String Query = "Delete from Account where account_id="+Id;
            Statement ADD = c.createStatement();
            ADD.executeUpdate(Query);
            JOptionPane.showMessageDialog(this, "Account Successfully Deleted");
            DisplayTable();
            txtAccName.setText("");
            txtAccPhoneNo.setText("");
            txtAccPin.setText("");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Select the row from table to Delete");
        }
    }//GEN-LAST:event_buttonAccDeleteActionPerformed

    private void buttonInvAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvAddActionPerformed
        try{
            if(txtInvName.getText().isEmpty() || txtInvPrice.getText().isEmpty() || txtInvDiscount.getText().isEmpty() || txtInvManufacturer.getText().isEmpty() || txtInvThreshold.getText().isEmpty()|| txtInvInventoryNo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
            }
            else{
                DatabaseFunctions.addInventory(txtInvName.getText(), Double.parseDouble(txtInvPrice.getText()), txtInvManufacturer.getText(), Integer.parseInt(txtInvThreshold.getText()), Double.parseDouble(txtInvInventoryNo.getText()));
                JOptionPane.showMessageDialog(this, "Inventory Successfully Added");
                DisplayTable();
                txtInvName.setText("");
                txtInvPrice.setText("");
                txtInvDiscount.setText("");
                txtInvManufacturer.setText("");
                txtInvThreshold.setText("");
                txtInvInventoryNo.setText("");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Input Correct Information");
        }
    }//GEN-LAST:event_buttonInvAddActionPerformed

    private void buttonInvDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvDeleteActionPerformed
        try{
            c = connect();
            DefaultTableModel model = (DefaultTableModel)tableInventory.getModel();
            int tbIndexInv = tableInventory.getSelectedRow();
            String IdInv = model.getValueAt(tbIndexInv, 0).toString();
            String QueryInv = "Delete from Inventory where item_id="+IdInv;
            Statement ADDInv = c.createStatement();
            ADDInv.executeUpdate(QueryInv);
            JOptionPane.showMessageDialog(this, "Item Successfully Deleted");
            DisplayTable();
            txtInvName.setText("");
            txtInvPrice.setText("");
            txtInvDiscount.setText("");
            txtInvManufacturer.setText("");
            txtInvThreshold.setText("");
            txtInvInventoryNo.setText("");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Select the row from table to Delete");
        }
    }//GEN-LAST:event_buttonInvDeleteActionPerformed

    private void buttonOrdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdUpdateActionPerformed
        if(tableOrders.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Select the row from table to Update");
        }
        else{
            try{
                c = connect();
                DefaultTableModel model = (DefaultTableModel)tableOrders.getModel();
                int tbIndexOrder = tableOrders.getSelectedRow();
                String QueryOrder = "Update Orders set status='"+txtOrdStatus.getText()+"'"+",item_amount='"+Integer.parseInt(txtItemAmt.getText().toString())+"'"+"where item_id="+model.getValueAt(tbIndexOrder, 2).toString();
                Statement ADDOrd = c.createStatement();
                ADDOrd.executeUpdate(QueryOrder);
                JOptionPane.showMessageDialog(this, "Order Successfully Updated");
                DisplayTable();
                txtOrdStatus.setText("");
                txtItemAmt.setText("");
            }
            catch(Exception SQL){
                SQL.printStackTrace();
                JOptionPane.showMessageDialog(this, "Invalid Input.");
            }
            
        } 
    }//GEN-LAST:event_buttonOrdUpdateActionPerformed

    private void tableAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountMouseClicked
        DefaultTableModel model = (DefaultTableModel)tableAccount.getModel();
        int tbIndex = tableAccount.getSelectedRow();
        txtAccName.setText(model.getValueAt(tbIndex, 4).toString());
        txtAccPin.setText(model.getValueAt(tbIndex, 1).toString());
        txtAccPhoneNo.setText(model.getValueAt(tbIndex, 5).toString());
    }//GEN-LAST:event_tableAccountMouseClicked

    private void buttonAccClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccClearActionPerformed
        txtAccName.setText("");
        txtAccPin.setText("");
        txtAccPhoneNo.setText("");
        DisplayTable();
    }//GEN-LAST:event_buttonAccClearActionPerformed

    private void buttonInvClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvClearActionPerformed
        txtInvName.setText("");
        txtInvPrice.setText("");
        txtInvDiscount.setText("");
        txtInvManufacturer.setText("");
        txtInvThreshold.setText("");
        txtInvInventoryNo.setText("");
        DisplayTable();
    }//GEN-LAST:event_buttonInvClearActionPerformed

    private void buttonOrdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdDeleteActionPerformed
        try{
            c = connect();
            DefaultTableModel model = (DefaultTableModel)tableOrders.getModel();
            int tbIndexOrd = tableOrders.getSelectedRow();
            String IdOrd = model.getValueAt(tbIndexOrd, 2).toString();
            String QueryOrd = "Delete from Orders where item_id="+IdOrd;
            Statement ADDOrd = c.createStatement();
            ADDOrd.executeUpdate(QueryOrd);
            JOptionPane.showMessageDialog(this, "Order Successfully Deleted");
            DisplayTable();
            txtOrdStatus.setText("");
            txtItemAmt.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Select the row from table to Delete");
        }
    }//GEN-LAST:event_buttonOrdDeleteActionPerformed

    private void tableOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrdersMouseClicked
        DefaultTableModel model = (DefaultTableModel)tableOrders.getModel();
        int tbIndexOrder = tableOrders.getSelectedRow();
        txtOrdStatus.setText(model.getValueAt(tbIndexOrder, 3).toString());
        txtItemAmt.setText(model.getValueAt(tbIndexOrder, 1).toString());
    }//GEN-LAST:event_tableOrdersMouseClicked

    private void runInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runInvActionPerformed
        RunInventoryControl.runInventory();
        JOptionPane.showMessageDialog(this, "Run Inventorory performed. Check Orders tab see items needed to be ordered.");
        DisplayTable();
    }//GEN-LAST:event_runInvActionPerformed

    private void buttonInvUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel)tableInventory.getModel();
        int tbIndexInv = tableInventory.getSelectedRow();
        if(tableInventory.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Select the row from table to Update");
        }
        else{
            try{
                c = connect();
                String QueryInv = "Update Inventory set item_name='"+txtInvName.getText()+"'"+",item_price="+Double.parseDouble(txtInvPrice.getText().toString())+",manufacturer='"+txtInvManufacturer.getText()+"'"+",item_threshold="+Integer.parseInt(txtInvThreshold.getText().toString())+",current_inventory="+Double.parseDouble(txtInvInventoryNo.getText().toString())+",item_discount="+Double.parseDouble(txtInvDiscount.getText().toString())+" where item_id="+model.getValueAt(tbIndexInv, 0).toString();
                Statement ADDInv = c.createStatement();
                ADDInv.executeUpdate(QueryInv);
                JOptionPane.showMessageDialog(this, "Item Successfully Updated");
                DisplayTable();
                txtInvName.setText("");
                txtInvPrice.setText("");
                txtInvManufacturer.setText("");
                txtInvThreshold.setText("");
                txtInvInventoryNo.setText("");
                txtInvDiscount.setText("");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Input correct Information");
            }
        }
    }//GEN-LAST:event_buttonInvUpdateActionPerformed

    private void tableInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInventoryMouseClicked
        DefaultTableModel model = (DefaultTableModel)tableInventory.getModel();
        int tbIndexInv = tableInventory.getSelectedRow();
        txtInvName.setText(model.getValueAt(tbIndexInv, 1).toString());
        txtInvPrice.setText(model.getValueAt(tbIndexInv, 2).toString());
        txtInvManufacturer.setText(model.getValueAt(tbIndexInv, 3).toString());
        txtInvThreshold.setText(model.getValueAt(tbIndexInv, 4).toString());
        txtInvInventoryNo.setText(model.getValueAt(tbIndexInv, 5).toString());
        txtInvDiscount.setText(model.getValueAt(tbIndexInv, 6).toString());
    }//GEN-LAST:event_tableInventoryMouseClicked

    private void buttonOrdApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdApproveActionPerformed
        DefaultTableModel model = (DefaultTableModel)tableOrders.getModel();
        int tbIndexOrd = tableOrders.getSelectedRow();
        if(tableOrders.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Select the row from table to Approve");
        }
        else{
            try{
                int id = Integer.parseInt(model.getValueAt(tbIndexOrd, 2).toString());
                RunInventoryControl.approveOrder(id);
                JOptionPane.showMessageDialog(this, "Approved Order. Waiting to send orders.");
                DisplayTable();
                txtOrdStatus.setText("");
                txtItemAmt.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error. Try again.");
            }
        }
    }//GEN-LAST:event_buttonOrdApproveActionPerformed

    private void buttonOrdReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdReceiveActionPerformed
        DefaultTableModel model = (DefaultTableModel)tableOrders.getModel();
        int tbIndexOrd = tableOrders.getSelectedRow();
        if(tableOrders.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Select the item from table that has been recieved");
        }
        else{
            try{
                int id = Integer.parseInt(model.getValueAt(tbIndexOrd, 2).toString());
                InventoryControl.recieveOrder(id);
                JOptionPane.showMessageDialog(this, "Order fulfilled.");
                DisplayTable();
                txtOrdStatus.setText("");
                txtItemAmt.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error. Try again.");
            }
        }
    }//GEN-LAST:event_buttonOrdReceiveActionPerformed

    private void buttonOrdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdClearActionPerformed
        DisplayTable();
        txtOrdStatus.setText("");
        txtItemAmt.setText("");
    }//GEN-LAST:event_buttonOrdClearActionPerformed

    private void buttonOrdSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdSendActionPerformed
        try{
            InventoryControl.sendOrders();
            JOptionPane.showMessageDialog(this, "Approved orders sent to the suppliers");
            DisplayTable();
            txtOrdStatus.setText("");
            txtItemAmt.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error sending the orders");
        }
        
    }//GEN-LAST:event_buttonOrdSendActionPerformed

    private void buttonOrdClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdClear1ActionPerformed
        DisplayTable();
    }//GEN-LAST:event_buttonOrdClear1ActionPerformed

    public void DisplayTable(){
        try{
            Class.forName("org.sqlite.JDBC");
            c = connect();
            String sqlAcc = "select * from Account";
            PreparedStatement pstmtAcc = c.prepareStatement(sqlAcc);
            ResultSet rsAcc = pstmtAcc.executeQuery();
            tableAccount.setModel(DbUtils.resultSetToTableModel(rsAcc));
            
            String sqlInv = "select * from Inventory";
            PreparedStatement pstmtInv = c.prepareStatement(sqlInv);
            ResultSet rsInv = pstmtInv.executeQuery();
            tableInventory.setModel(DbUtils.resultSetToTableModel(rsInv));
            
            String sqlOrd = "select * from Orders";
            PreparedStatement pstmtOrd = c.prepareStatement(sqlOrd);
            ResultSet rsOrd = pstmtOrd.executeQuery();
            tableOrders.setModel(DbUtils.resultSetToTableModel(rsOrd));
            
            String sqlPur = "select * from Purchase";
            PreparedStatement pstmtPur = c.prepareStatement(sqlPur);
            ResultSet rsPur = pstmtPur.executeQuery();
            tablePurchase.setModel(DbUtils.resultSetToTableModel(rsPur));
        }
        catch(Exception e){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account;
    private javax.swing.JPanel Inventory;
    private javax.swing.JPanel Orders;
    private javax.swing.JPanel Purchases;
    private javax.swing.JButton buttonAccAdd;
    private javax.swing.JButton buttonAccClear;
    private javax.swing.JButton buttonAccDelete;
    private javax.swing.JButton buttonInvAdd;
    private javax.swing.JButton buttonInvClear;
    private javax.swing.JButton buttonInvDelete;
    private javax.swing.JButton buttonInvUpdate;
    private javax.swing.JButton buttonOrdApprove;
    private javax.swing.JButton buttonOrdClear;
    private javax.swing.JButton buttonOrdClear1;
    private javax.swing.JButton buttonOrdDelete;
    private javax.swing.JButton buttonOrdReceive;
    private javax.swing.JButton buttonOrdSend;
    private javax.swing.JButton buttonOrdUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton runInv;
    private javax.swing.JTable tableAccount;
    private javax.swing.JTable tableInventory;
    private javax.swing.JTable tableOrders;
    private javax.swing.JTable tablePurchase;
    private javax.swing.JTextField txtAccName;
    private javax.swing.JTextField txtAccPhoneNo;
    private javax.swing.JTextField txtAccPin;
    private javax.swing.JComboBox<String> txtAccRole;
    private javax.swing.JTextField txtInvDiscount;
    private javax.swing.JTextField txtInvInventoryNo;
    private javax.swing.JTextField txtInvManufacturer;
    private javax.swing.JTextField txtInvName;
    private javax.swing.JTextField txtInvPrice;
    private javax.swing.JTextField txtInvThreshold;
    private javax.swing.JTextField txtItemAmt;
    private javax.swing.JTextField txtOrdStatus;
    // End of variables declaration//GEN-END:variables
}
